@startuml
!include style.plantuml
left to right direction

class Thing #silver
package dpv {
	class Context
	class Importance
	class Necessity
	class Entity
	class Technology
	class Justification
	class Frequency
	class Duration
	class Scope
	class Status
	class ActivityStatus
	class AuditStatus
	class RequestStatus
	class ComplianceStatus
	class Lawfulness
}

Thing -- Context: hasContext >
Thing -- Importance: hasImportance >
Thing -- Necessity: hasNecessity >
Thing -- Entity: hasEntity >
Thing -- Technology: hasTechnology >
Thing -- Justification: hasJustification >
Thing -- Frequency: hasFrequency >
Thing -- Duration: hasDuration >
Thing -- Scope: hasScope >
Thing -- Status: hasStatus >
Thing -- ActivityStatus: hasActivityStatus >
Thing -- AuditStatus: hasAuditStatus >
Thing -- RequestStatus: hasRequestStatus >
Thing -- ComplianceStatus: hasComplianceStatus >
Thing -- Lawfulness: hasLawfulness >

Thing --- Thing: hasIdentifier >
Thing --- Thing: hasOutcome >
Thing --- Thing: isAfter >
Thing --- Thing: isBefore >

@enduml
