@startuml
!include include/style.plantuml
left to right direction


package dpv {
	
	' Core Concepts
	class Process
	class Data
	class PersonalData
	class Purpose
	class DataController
	class DataSubject
	class Recipient
	class Context
	class Risk
	class OrgnaizationalMeasure
	class TechnicalMeasure
	class Right
	class LegalBasis
	class Processing 
	class Technology
	
	PersonalData --|>Data
	
	Process --> Data: hasData >
	Process --> PersonalData : hasPersonalData >
	Process --> Purpose: hasPurpose >
	Process --> Processing: hasProcessing >
	Process --> Entity: hasEntity >
	Process --> DataController: hasDataController >
	Process --> DataSubject: hasDataSubject >
	Process --> Recipient: hasRecipient >
	Process --> TechnicalMeasure: hasTechnicalMeasure >
	Process --> OrgnaizationalMeasure: hasOrganizationalMeasure >
	Process --> LegalBasis: hasLegalBasis >
	Process --> Right: hasRight >
	Process --> Risk: hasRisk >
	Process --> Context: hasContext >
	Process --> Technology: isImplementedUsingTechnology >

	' 2. Process
	class PersonalDataHandling {}
	PersonalDataHandling --|> Process
	class NonPersonalDataProcess {}
	NonPersonalDataProcess --|> Process
	class PersonalDataProcess {}
	PersonalDataProcess --|> Process
	class Service {}
	Service --|> Process

	' LegalBases
	
	package pd {}
	PersonalData --> pd
	
	package risk {}
	Risk --> risk
	
	package tech {}
	Technology --> tech
	
	package legal {}
	LegalBasis --> legal
	
	package justifications {}
	remove justifications
	
	package loc {}
	remove loc
	
	package ai {}
	remove ai

	}
	

	
	@enduml
