@startuml
!include style.plantuml
left to right direction

class Thing
class Representative
class DataController
class DataProcessor
class ThirdParty
class Authority
class DataSubject
class LegalEntity
class NaturalPerson
class Entity

Representative -|> LegalEntity 
DataController -|> LegalEntity
DataProcessor -|> LegalEntity
ThirdParty -|> LegalEntity
Authority -|> LegalEntity
DataSubject -|> LegalEntity
DataSubject -|> NaturalPerson
LegalEntity -|> Entity
NaturalPerson -|> Entity

Thing -> Representative: hasRepresentative
Thing -> DataController: hasDataController
Thing -> DataProcessor: hasDataProcessor
Thing -> ThirdParty: hasThirdParty
Thing -> Authority: hasAuthority
Thing -> DataSubject: hasDataSubject

Representative -[hidden]d- DataController
DataController -[hidden]d- DataProcessor
DataProcessor -[hidden]d- ThirdParty
ThirdParty -[hidden]d- Authority
Authority -[hidden]d- DataSubject
LegalEntity -[hidden]d- NaturalPerson


@enduml
