@startuml
!include include/style.plantuml
left to right direction
'top to bottom direction

class Thing
class DataProcessor
class DataController
class ThirdParty
class Recipient

DataController -[hidden]- DataProcessor
DataController -[hidden]- ThirdParty

DataController -|> Recipient
DataProcessor -|> Recipient
ThirdParty -|> Recipient

Thing -> Recipient : hasRecipient
Thing -> DataController: hasRecipientDataController
Thing -> DataProcessor: hasRecipientDataProcessor
Thing -> ThirdParty : hasRecipientThirdParty

@enduml
