@startuml
!include style.plantuml
left to right direction

class Thing
class PersonalData
class SensitivePersonalData
class SpecialCategoryPersonalData

Thing --> PersonalData : hasPersonalData
PersonalData <|-- SensitivePersonalData
SensitivePersonalData <|-- SpecialCategoryPersonalData

@enduml
