@startuml
!include style.plantuml
'left to right direction
top to bottom direction

class Thing #silver
package dpv {
	class TechnicalOrganisationalMeasure
	class TechnicalMeasure
	class OrganisationalMeasure
	class LegalMeasure
	class PhysicalMeasure
}

TechnicalOrganisationalMeasure <|-- TechnicalMeasure
TechnicalOrganisationalMeasure <|-- OrganisationalMeasure
TechnicalOrganisationalMeasure <|-- LegalMeasure
TechnicalOrganisationalMeasure <|-- PhysicalMeasure

Thing -- TechnicalOrganisationalMeasure : hasTechnicalOrganisationalMeasure >
Thing -- OrganisationalMeasure : hasOrganisationalMeasure >
Thing -- TechnicalMeasure : hasTechnicalMeasure >
Thing -- LegalMeasure : hasLegalMeasure >
Thing -- PhysicalMeasure : hasPhysicalMeasure >


@enduml
