@startuml
!include style.plantuml
'left to right direction

class Thing #silver
package dpv {
	class TechnicalOrganisationalMeasure
	class RiskMitigationMeasure
	class TechnicalMeasure
	class OrganisationalMeasure
	class Risk
	class Notice
	class Policy
}

TechnicalOrganisationalMeasure <|-- TechnicalMeasure
TechnicalOrganisationalMeasure <|-- RiskMitigationMeasure
TechnicalOrganisationalMeasure <|-- OrganisationalMeasure
OrganisationalMeasure <|-- Notice
OrganisationalMeasure <|-- Policy

Thing -- TechnicalOrganisationalMeasure : hasTechnicalOrganisationalMeasure >
Thing -- TechnicalMeasure : hasTechnicalMeasure >
Thing -- Risk : hasRisk >
Thing -- Notice : hasNotice >
Thing -- Policy : hasPolicy >
Risk -- RiskMitigationMeasure: isMitigatedByMeasure >
RiskMitigationMeasure -- Risk: mitigatesRisk >
Policy -- Thing: isPolicyFor >

@enduml
