@startuml
!include style.plantuml
'skinParam groupInheritance 2
left to right direction

package dpv {
	class Process
	class LegalBasis
	class Principle
	class OrganisationalMeasure
	class DataSubjectRight
	class Organisation
	class DataProtectionAuthority
	class Lawfulness
	class Dpia as "DPIA"
}

package dpv.risk {
	class Incident
}

Process -- LegalBasis: hasLegalBasis >
Process -- OrganisationalMeasure: hasOrganisationalMeasure >
Process -- Principle: hasOrganisationalMeasure >
Process -- DataSubjectRight: hasRight >
Process -- Organisation: hasEntity >
Process -- Lawfulness: hasLawfulness >
Process -- DataProtectionAuthority: hasAuthority >
Process -- Dpia: hasImpactAssessment >
Process -- Incident: hasIncident >


package dpv.legal.eu.gdpr {
	abstract class LegalBasesA6 as "[[../legal/eu/gdpr/index.html#vocab-legal-basis-core Core legal bases\nas defined by GDPR Art. 6]]" #LightBlue
	abstract class LegalBasesSpecialA9 as "[[../legal/eu/gdpr/index.html#vocab-legal-basis-special Legal bases for special\ncategory personal data\nas defined by GDPR Art. 9]]" #LightBlue
	abstract class LegalBasesDataTransfersA45_49 as "[[../legal/eu/gdpr/index.html#vocab-legal-basis-data-transfer Legal bases for\ndata transfer\nas defined by GDPR Art. 45-49]]" #LightBlue
	abstract class PrinciplesA5 as "[[../legal/eu/gdpr/index.html#vocab-principles Principles for personal\ndata processing\nas defined by GDPR Art. 5]]" #LightBlue
	abstract class DataSubjectRightsGDPR as "[[../legal/eu/gdpr/index.html#vocab-rights Data subject rights\nas defined by GDPR]]" #LightBlue
	abstract class DataTransferToolsGDPR as "[[../legal/eu/gdpr/index.html#vocab-data-transfers Data transfer tools\nas defined by GDPR]]" #LightBlue
	abstract class GdprDpia as "[[../legal/eu/gdpr/index.html#vocab-dpia DPIA concepts\nas defined by GDPR]]" #LightBlue
	abstract class DataBreachObligations as "[[../legal/eu/gdpr/index.html#vocab-data-breach Data breach obligations\nas defined by GDPR]]" #LightBlue
	class Establishment as "[[../legal/eu/gdpr/index.html#vocab-entities-establishment Establishment variants\nas defined by GDPR]]" #LightBlue
	class GdprDataProtectionAuthority as "[[../legal/eu/gdpr/index.html#vocab-entities-authorities Data Protection Authorities\nas defined by GDPR]]" #LightBlue
	class GDPRLawfulness as "[[../legal/eu/gdpr/index.html#vocab-compliance Lawfulness as\ndefined by GDPR]]" #LightBlue
}

Principle <|-[dashed]- PrinciplesA5
DataSubjectRight <|-[dashed]- DataSubjectRightsGDPR
OrganisationalMeasure <|-[dashed]- DataTransferToolsGDPR
Incident <|-[dashed]- DataBreachObligations
Organisation <|-[dashed]- Establishment
DataProtectionAuthority <|-[dashed]- GdprDataProtectionAuthority
Lawfulness <|-[dashed]- GDPRLawfulness
Dpia <|-[dashed]- GdprDpia
LegalBasis <|-[dashed]- LegalBasesA6
LegalBasis <|-[dashed]- LegalBasesSpecialA9
LegalBasis <|-[dashed]- LegalBasesDataTransfersA45_49

@enduml
